# Problem: benchmarking_script (10 points)

End-to-end benchmarking of forward and backward passes for `BasicsTransformerLM`.

In [1]:
import math
import timeit

import torch
import pandas as pd
from a1_basics.model import BasicsTransformerLM
from student.basicprofiling import benchmark, MODEL_SIZES

In [ ]:
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {DEVICE}")
if DEVICE == "cuda":
    print(torch.cuda.get_device_name())

## Part (b): Time forward and backward passes for all model sizes

Use 5 warmup steps, 10 measurement steps. Report average and standard deviation.

Set `USE_SLURM_RESULTS = True` below to load pre-computed results from sbatch jobs, or `False` to run live in this notebook.

In [3]:
USE_SLURM_RESULTS = True  # Toggle: True = load from sbatch CSVs, False = run live

if USE_SLURM_RESULTS:
    # --- Load pre-computed results from sbatch ---
    import os
    csv_path = os.path.join(os.path.dirname("__file__"), "../results", "bench_part_b.csv")
    # If running on HPC, adjust path:
    # csv_path = "/scratch/pg2973/nyu-llm-reasoners-a2/results/bench_part_b.csv"
    df_b = pd.read_csv(csv_path)
    # Normalize mode names to match notebook convention
    df_b["mode"] = df_b["mode"].replace({
        "forward-only": "forward",
        "forward-backward": "forward+backward",
    })
    print(f"Loaded {len(df_b)} rows from {csv_path}")
    display(df_b)

Loaded 10 rows from ../results/bench_part_b.csv

    model              mode  avg_ms  std_ms  min_ms  max_ms  peak_mem_mb
0   small  forward+backward   74.49    1.43   73.35   78.50      1232.69
1   small           forward   36.64    0.38   36.34   37.46      1164.56
2  medium  forward+backward  153.03    3.83  151.02  164.38      3374.70
3  medium           forward   73.37    0.20   73.02   73.77      3286.57
4   large  forward+backward  269.29    1.00  267.78  271.30      7696.14
5   large           forward  112.54    1.73  110.66  116.81      6908.85
6      xl  forward+backward  455.04    1.61  453.85  459.74     15684.55
7      xl           forward  152.65    0.63  151.70  153.69     12953.12
8    2.7B  forward+backward  676.29    0.09  676.18  676.45     26255.56
9    2.7B           forward  223.86    0.28  223.30  224.33     18488.93

In [4]:
USE_SLURM_RESULTS = True

if USE_SLURM_RESULTS:
    import os
    import pandas as pd
    from IPython.display import display

    csv_path = os.path.join(os.path.dirname("__file__"), "../results", "bench_part_b.csv")
    df_b = pd.read_csv(csv_path)
    df_b["mode"] = df_b["mode"].replace({
        "forward-only": "forward",
        "forward-backward": "forward+backward",
    })
    print(f"Loaded {len(df_b)} rows from {csv_path}")

    # ── 1. Display pandas table ───────────────────────────────────────────────
    display(df_b)

    # ── 2. Build derived table (fwd vs fwd+bwd side by side) ─────────────────
    fwd   = df_b[df_b["mode"] == "forward"].set_index("model")
    fwdbw = df_b[df_b["mode"] == "forward+backward"].set_index("model")

    PARAMS = {
        "small":  "121M",
        "medium": "413M",
        "large":  "957M",
        "xl":     "1.98B",
        "2.7B":   "3.38B",
    }

    rows = []
    for model in ["small", "medium", "large", "xl", "2.7B"]:
        fwd_avg  = fwd.loc[model, "avg_ms"]
        fwd_std  = fwd.loc[model, "std_ms"]
        bw_avg   = fwdbw.loc[model, "avg_ms"]
        bw_std   = fwdbw.loc[model, "std_ms"]
        bwd_alone = round(bw_avg - fwd_avg, 2)
        ratio     = round(bwd_alone / fwd_avg, 2)
        rows.append({
            "Model":        model,
            "Params":       PARAMS[model],
            "Fwd avg (ms)": fwd_avg,
            "Fwd std (ms)": fwd_std,
            "Fwd+Bwd avg (ms)": bw_avg,
            "Fwd+Bwd std (ms)": bw_std,
            "Bwd alone (ms)":   bwd_alone,
            "Bwd/Fwd":          ratio,
        })

    df_derived = pd.DataFrame(rows)
    print("\nDerived table:")
    display(df_derived)

    # ── 3. Print LaTeX ────────────────────────────────────────────────────────
    latex = df_derived.to_latex(
        index=False,
        float_format="%.2f",
        caption=(
            "Forward and backward pass timings (ms) at context length 128, "
            "batch size 4, 5 warm-up steps, 10 measurement steps. GPU: A100. "
            "Bwd alone is derived as (Fwd+Bwd) $-$ Fwd."
        ),
        label="tab:bench_partb",
        column_format="lrrrrrrr",
        escape=False,
    )

    # Wrap in table[H] and add booktabs-style rules
    latex = latex.replace("\\begin{table}", "\\begin{table}[H]")

    print("\nLaTeX output:")
    print(latex)

Loaded 10 rows from ../results/bench_part_b.csv

    model              mode  avg_ms  std_ms  min_ms  max_ms  peak_mem_mb
0   small  forward+backward   74.49    1.43   73.35   78.50      1232.69
1   small           forward   36.64    0.38   36.34   37.46      1164.56
2  medium  forward+backward  153.03    3.83  151.02  164.38      3374.70
3  medium           forward   73.37    0.20   73.02   73.77      3286.57
4   large  forward+backward  269.29    1.00  267.78  271.30      7696.14
5   large           forward  112.54    1.73  110.66  116.81      6908.85
6      xl  forward+backward  455.04    1.61  453.85  459.74     15684.55
7      xl           forward  152.65    0.63  151.70  153.69     12953.12
8    2.7B  forward+backward  676.29    0.09  676.18  676.45     26255.56
9    2.7B           forward  223.86    0.28  223.30  224.33     18488.93

Derived table:

,Model,Params,Fwd avg (ms),Fwd std (ms),Fwd+Bwd avg (ms),Fwd+Bwd std (ms),Bwd alone (ms),Bwd/Fwd
0,small,121M,36.64,0.38,74.49,1.43,37.85,1.03
1,medium,413M,73.37,0.20,153.03,3.83,79.66,1.09
2,large,957M,112.54,1.73,269.29,1.00,156.75,1.39
3,xl,1.98B,152.65,0.63,455.04,1.61,302.39,1.98
4,2.7B,3.38B,223.86,0.28,676.29,0.09,452.43,2.02

LaTeX output:
\begin{table}[H]
\caption{Forward and backward pass timings (ms) at context length 128, batch size 4, 5 warm-up steps, 10 measurement steps. GPU: A100. Bwd alone is derived as (Fwd+Bwd) $-$ Fwd.}
\label{tab:bench_partb}
\begin{tabular}{lrrrrrrr}
\toprule
Model & Params & Fwd avg (ms) & Fwd std (ms) & Fwd+Bwd avg (ms) & Fwd+Bwd std (ms) & Bwd alone (ms) & Bwd/Fwd \\
\midrule
small & 121M & 36.64 & 0.38 & 74.49 & 1.43 & 37.85 & 1.03 \\
medium & 413M & 73.37 & 0.20 & 153.03 & 3.83 & 79.66 & 1.09 \\
large & 957M & 112.54 & 1.73 & 269.29 & 1.00 & 156.75 & 1.39 \\
xl & 1.98B & 152.65 & 0.63 & 455.04 & 1.61 & 302.39 & 1.98 \\
2.7B & 3.38B & 223.86 & 0.28 & 676.29 & 0.09 & 452.43 & 2.02 \\
\bottomrule
\end{tabular}
\end{table}

In [ ]:
df_b = pd.DataFrame(results)

# Pivot into a readable table: rows = (model, ctx_len), columns = mode
pivot_avg = df_b.pivot_table(index=["model", "ctx_len"], columns="mode", values="avg_ms", aggfunc="first")
pivot_std = df_b.pivot_table(index=["model", "ctx_len"], columns="mode", values="std_ms", aggfunc="first")

# Combine avg ± std into a single string per cell
def fmt_cell(avg, std):
    if avg == "OOM" or std == "OOM":
        return "OOM"
    return f"{avg:.2f} ± {std:.2f}"

combined = pd.DataFrame(index=pivot_avg.index)
for col in pivot_avg.columns:
    combined[col] = [
        fmt_cell(a, s) for a, s in zip(pivot_avg[col], pivot_std[col])
    ]

combined.columns.name = None
combined = combined.rename(columns={"forward": "Forward (ms)", "forward+backward": "Fwd+Bwd (ms)"})

print("=== Markdown ===")
print(combined.to_markdown())
print()
print("=== LaTeX ===")
print(combined.to_latex())

combined

### Part (b) response

_Fill in after running:_ A 1-2 sentence response with your timings.

## Part (c): Effect of warm-up steps

Repeat the analysis with 0, 1, 2, and 5 warm-up steps to see the effect.

Uses the same `USE_SLURM_RESULTS` toggle from above.

In [ ]:

# --- Load pre-computed results from sbatch ---
csv_path = os.path.join(os.path.dirname("__file__"), "results", "bench_part_c.csv")
# If running on HPC, adjust path:
# csv_path = "/scratch/pg2973/nyu-llm-reasoners-a2/results/bench_part_c.csv"
df_c = pd.read_csv(csv_path)
df_c["mode"] = df_c["mode"].replace({
    "forward-only": "forward",
    "forward-backward": "forward+backward",
})
print(f"Loaded {len(df_c)} rows from {csv_path}")
display(df_c)

In [5]:
import os
import pandas as pd
from IPython.display import display

# ── Load part c CSV (warmup 0, 1, 2) ─────────────────────────────────────────
csv_path_c = os.path.join(os.path.dirname("__file__"), "../results", "bench_part_c.csv")
df_c = pd.read_csv(csv_path_c)
df_c["mode"] = df_c["mode"].replace({
    "forward-only": "forward",
    "forward-backward": "forward+backward",
})

# ── Append warmup=5 rows from part b (already have this data, no re-run needed)
csv_path_b = os.path.join(os.path.dirname("__file__"), "../results", "bench_part_b.csv")
df_b = pd.read_csv(csv_path_b)
df_b["mode"] = df_b["mode"].replace({
    "forward-only": "forward",
    "forward-backward": "forward+backward",
})

# Pull only small model rows from part b and tag with warmup_steps=5
df_b5 = df_b[df_b["model"] == "small"][["model", "mode", "avg_ms", "std_ms", "min_ms", "max_ms"]].copy()
df_b5.insert(2, "warmup_steps", 5)

# Combine and sort
df_c_full = pd.concat([df_c, df_b5], ignore_index=True)
df_c_full = df_c_full.sort_values(["mode", "warmup_steps"]).reset_index(drop=True)

print(f"Loaded {len(df_c)} rows from part c + {len(df_b5)} rows from part b (warmup=5)")
print("\nFull part c table:")
display(df_c_full)

# ── LaTeX ─────────────────────────────────────────────────────────────────────
latex = df_c_full[["model", "mode", "warmup_steps", "avg_ms", "std_ms", "min_ms", "max_ms"]].to_latex(
    index=False,
    float_format="%.2f",
    columns=["mode", "warmup_steps", "avg_ms", "std_ms", "min_ms", "max_ms"],
    header=["Mode", "Warmup Steps", "Avg (ms)", "Std (ms)", "Min (ms)", "Max (ms)"],
    caption=(
        "Effect of warm-up steps on timing measurements for the small model "
        "at context length 128, batch size 4, 10 measurement steps. "
        "Warmup=5 rows are taken from Table~\\ref{tab:bench_partb}."
    ),
    label="tab:bench_partc",
    column_format="lrrrrr",
    escape=False,
)
latex = latex.replace("\\begin{table}", "\\begin{table}[H]")

print("\nLaTeX output:")
print(latex)

Loaded 6 rows from part c + 2 rows from part b (warmup=5)

Full part c table:

   model              mode  warmup_steps  avg_ms  std_ms  min_ms   max_ms
0  small           forward             0   87.93  150.11   37.61   538.27
1  small           forward             1   36.61    0.18   36.31    36.88
2  small           forward             2   37.10    0.23   36.69    37.48
3  small           forward             5   36.64    0.38   36.34    37.46
4  small  forward+backward             0  266.54  570.99   74.83  1979.51
5  small  forward+backward             1   77.41    2.93   74.18    83.74
6  small  forward+backward             2   75.74    0.98   75.00    78.48
7  small  forward+backward             5   74.49    1.43   73.35    78.50

LaTeX output:
\begin{table}[H]
\caption{Effect of warm-up steps on timing measurements for the small model at context length 128, batch size 4, 10 measurement steps. Warmup=5 rows are taken from Table~\ref{tab:bench_partb}.}
\label{tab:bench_partc}
\begin{tabular}{lrrrrr}
\toprule
Mode & Warmup Steps & Avg (ms) & Std (ms) & Min (ms) & Max (ms) \\
\midrule
forward & 0 & 87.93 & 150.11 & 37.61 & 538.27 \\
forward & 1 & 36.61 & 0.18 & 36.31 & 36.88 \\
forward & 2 & 37.10 & 0.23 & 36.69 & 37.48 \\
forward & 5 & 36.64 & 0.38 & 36.34 & 37.46 \\
forward+backward & 0 & 266.54 & 570.99 & 74.83 & 1979.51 \\
forward+backward & 1 & 77.41 & 2.93 & 74.18 & 83.74 \\
forward+backward & 2 & 75.74 & 0.98 & 75.00 & 78.48 \\
forward+backward & 5 & 74.49 & 1.43 & 73.35 & 78.50 \\
\bottomrule
\end{tabular}
\end{table}

In [ ]:
# Normalize column name
if "warmup_steps" in df_c.columns:
    df_c = df_c.rename(columns={"warmup_steps": "warmup"})

pivot_avg = df_c.pivot_table(index="warmup", columns="mode", values="avg_ms", aggfunc="first")
pivot_std = df_c.pivot_table(index="warmup", columns="mode", values="std_ms", aggfunc="first")

table_c = pd.DataFrame(index=pivot_avg.index)
for col in pivot_avg.columns:
    table_c[f"{col} avg±std (ms)"] = [
        f"{a:.2f} ± {s:.2f}" for a, s in zip(pivot_avg[col], pivot_std[col])
    ]

# Add first-step column if available (live runs only)
if "first_step_ms" in df_c.columns:
    pivot_first = df_c.pivot_table(index="warmup", columns="mode", values="first_step_ms", aggfunc="first")
    for col in pivot_first.columns:
        table_c[f"{col} 1st step (ms)"] = [f"{v:.2f}" for v in pivot_first[col]]

table_c.columns.name = None
table_c.index.name = "warmup"

print("=== Markdown ===")
print(table_c.to_markdown())
print()
print("=== LaTeX ===")
print(table_c.to_latex())

table_c

### Part (c) response

_Fill in after running:_ A 2-3 sentence response.

In [6]:
s = torch.tensor(0,dtype=torch.float32)
for i in range(1000):
    s += torch.tensor(0.01,dtype=torch.float32)
print(s)
s = torch.tensor(0,dtype=torch.float16)
for i in range(1000):
    s += torch.tensor(0.01,dtype=torch.float16)
print(s)
s = torch.tensor(0,dtype=torch.float32)
for i in range(1000):
    s += torch.tensor(0.01,dtype=torch.float16)
print(s)
s = torch.tensor(0,dtype=torch.float32)
for i in range(1000):
    x = torch.tensor(0.01,dtype=torch.float16)
    s += x.type(torch.float32)
print(s)

tensor(10.0001)
tensor(9.9531, dtype=torch.float16)
tensor(10.0021)
tensor(10.0021)

In [ ]:
tensor(10.0001)
tensor(9.9531, dtype=torch.float16)
tensor(10.0021)
tensor(10.0021)